基本完成了社团管理的前端部分，添加了后端文件
exorteam/Exort pull request #18
Opened 2019-07-04 09:01 UTC by jinyuchencn

2019-07-04 09:45 UTC, icecola2018 requested changes

2019-07-04 09:45 UTC, icecola2018 commented on .vscode/settings.json
> +{
不要把vscode配置文件提交上来

解决方案
```
$ echo "**/**" > .vscode/.gitignore
```

2019-07-04 09:45 UTC, icecola2018 commented on FrontEnd/package-lock.json
>          "ansi-regex": {
可能是npm版本问题

2019-07-04 09:45 UTC, icecola2018 commented on FrontEnd/src/App.vue
>            </MenuItem>
什么意思。。。

2019-07-04 09:45 UTC, icecola2018 commented on FrontEnd/src/router/index.js
> +import Test from '../components/association_management/create_Test'
这个没有用到

2019-07-04 09:45 UTC, icecola2018 commented on association_management/.idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
不要把idea配置文件放进来

2019-07-04 10:36 UTC, jinyuchencn commented on .vscode/settings.json
> +{
OK

2019-07-05 01:02 UTC, Bert-Z approved these changes

2019-07-05 01:02 UTC, Bert-Z commented on FrontEnd/src/App.vue
>            </MenuItem>
侧栏和导航栏之后再敲定，之前先尽量不要动

2019-07-05 02:01 UTC, Bert-Z approved these changes

2019-07-05 02:01 UTC, merged