Activity management interface
exorteam/Exort pull request #66
Opened 2019-07-09 06:34 UTC by ruishaopu561

2019-07-10 16:22 UTC, Bert-Z commented on activity_manager/doc/activity_management_spec_http.md
> +      - 400
这边举一下例子说什么时候会出现这种错误吧，下同，具体形式参看沈小洲的对应md

2019-07-10 16:22 UTC, Bert-Z commented on activity_manager/doc/activity_management_spec_http.md
> +             "id"： 21，
这里md的显示有些奇怪，下同

2019-07-10 16:22 UTC, Bert-Z commented on activity_manager/doc/activity_management_spec_http.md
> +   - Query Parameters
这里传参也是Query Params里面只放页码、每页数量和sortby吧，另外一部分放到Body Params里面吧，具体参看沈小洲的md

2019-07-11 01:25 UTC, icecola2018 requested changes

2019-07-11 01:25 UTC, icecola2018 commented on activity_manager/doc/activity_management_spec_http.md
> +- **Activity**
先描述一下Activity的内容

2019-07-11 01:25 UTC, icecola2018 commented on activity_manager/doc/activity_management_spec_http.md
> +      |200-(活动对象)|创建成功|
先在前面描述下活动对象

2019-07-11 01:25 UTC, icecola2018 commented on activity_manager/doc/activity_management_spec_http.md
> +      |bool ifOnlyAsso|活动是否仅社团成员可参加|false|
query parameter放
- pageSize
- pageNum
- sortBy

其他的放 body parameter

2019-07-11 01:25 UTC, icecola2018 commented on activity_manager/doc/activity_management_spec_http.md
> +         - error: "ywe"
ywe是什么意思

2019-07-11 01:25 UTC, icecola2018 commented on activity_manager/doc/activity_management_spec_http.md
> +         - error: "ywe"
ywe是什么意思

2019-07-11 01:25 UTC, icecola2018 commented on activity_manager/doc/activity_management_spec_http.md
> +   - 输入
....这后面可以删了吧

2019-07-11 01:26 UTC, closed without merging